### ISSUE TITLE
pridat nutne odôvodnenie preco sa student nezucastni eventu pri stlaceni "nezúčastnim sa"

### ISSUE THREAD

**Issue by sabolukas** [Nexteria/Nextis#96]

**Comment by ddeath** [comment]
@lukas-s  sme si isty ze takuto buzeraciu tam chceme mat?

Lebo je rozdiel ci poviem "nezucastnim sa" - tuto moznost ma uzivatel len vtedy ked sa este nevyjadril ci pride / nepride a druha moznost je "Odhlasit sa" - ak uzivatel uz raz zadal, ze pride a potom si to rozmyslel - v tomto pripade sa od neho pozaduje aj vysvetlenie

**Comment by sabolukas** [comment]
poziadavka je aby musel zadavat preco sa nezucastni aj ked zada "nezucastnim sa"

**Comment by ddeath** [comment]
a viest uviest aj ake su za tym argumenty? Je to prediskutovane a rozmyslene?
Berie sa do uvahy ze momentalne sa pozve na eventy 130 ludi a z toho horkotazko 30 da vediet ze ci pridu alebo nie? A my to ideme este stazit. Ved mali problem o sebe v profile napisat nieco...

Ok a kolko povinnych znakov tam ma byt?

**Comment by martinmojzes** [comment]
Ahojte.
Toto som si nahodou vsimol ako issue. Stotoznujem sa s Dusanovymi otazkami. Predpokladam, ze prisiel podnet od Dandy a z jej pohladu to dava uplne zmysel, no mali by sme si taketo podnety (pripadne aj vsetky, ak nejde o bug) najprv prediskutovat (cize mal by som ich v nejakej forme vidiet a v pripade nejasnosti schvalit/neschvalit). Mozeme nastavit "schvalovaci" proces aj inac kedze aj nie kazdy podnet od studentov je automaticky relevantny - dokonca moze ist proti logike systemu. Nech sa nestane, ze jeden tyzden dame poziadavku nieco taketo urobit a dalsi tyzden dame poziadavku to zrusit.

Ale k poziadavke teda.
**Nedaval by som to ako povinnu vec.** 
Ak to vieme urobit nejak neotravne ako nepovinnu s dovysvetlenim, preco nas to zaujima (v strucnosti: ak mame informaciu, tak sa na jej zaklade vieme zariadit nabuduce - napr. ked 6 ludi napise, ze su chori ci maju rodinnu oslavu, je to ine, nez ked napisu, ze idu na nejaky zaujimavy workshop), tak by nam to pomohlo. Napr. po stlaceni by vyskocila z buttonu bublina, ktora sa da odignorovat, alebo dopisat dovod (neberte to ako dizajnovu specifikaciu, brainstormujem).

Ak to takto nevieme urobit, je pre nas dolezitejsie, aby sa naucili klikat aspon nieco, nez to neklikat, lebo sa im nechce vyplnat dovod (otrava, hanba, just nekliknem, ...).
